// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzrdgekunypjyzsmszlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cmRnZWt1bnlwanl6c21zemxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTQzNjQsImV4cCI6MjA2NDUzMDM2NH0.-8b4apUzyKLWeeIA4EbczJu5J7a_RTMeKBOJUp0z6VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);